name: Build and Test

on: push

jobs:
  test:
    # Needed to make puppeteer work on GitHub Actions
    # See https://github.com/puppeteer/puppeteer/issues/12818
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        hugo-version: ['0.152.2', '0.162.1']
    steps:

    # This is needed by puppeteer
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libgbm-dev

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ matrix.hugo-version }}

    - uses: actions/checkout@v3
      with:
        repository: gauntface/hugo-base-theme-test
    - uses: actions/checkout@v3
      with:
        path: example-site/themes/base-theme/

    - name: Install
      run: npm install

    - name: Test
      run: npm run test

  build-and-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "All Hugo versions passed"
